### ISSUE TITLE
Criação da catraca virtual

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#1]
Esta issue não está vinculada a nenhum requisito, uma vez que a catraca é um sistema externo. Contudo, para o funcionamento regular do programa, é necessário implementar um mecanismo de "catraca", melhor descrito abaixo:

Como responsável pelo estabelecimento do restaurante universitário, gostaria que apenas pessoas autorizadas, isto é, os clientes que possuam tíquete para a refeição a ser servida, possam adentrar o local através da catraca de segurança.

A catraca será apenas uma representação similar a uma catraca física. Para tal, ela deve estar constantemente travada/fechada. Ela será aberta temporariamente apenas após receber um sinal do programa que administra os tíquetes do RU.
Após ser acionada, irá abrir uma janela com um botão que representam a abertura e a passagem do cliente pela catraca. O pressionamento do botão significa a passagem do cliente pela passagem. A partir deste momento, a catraca é fechada novamente.

GanttStart: 2022-12-07
GanttDue: 2022-12-22

**Comment by GuiCT** [comment]
Inclui uma classe boundary no arquivo .asta cujo objetivo é representar o funcionamento da catraca.

**Comment by Salies** [comment]
Criada a catraca. A interação via socket está funcional. 
Contudo, o sistema ainda não interage com ela, visto que isto é contemplado apenas pela issue #8.

Código no PR #17.

Aguardo SQA.
