### ISSUE TITLE
Login e Representação dos usuários na aplicação

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#2]
Como gerente do projeto, gostaria que houvesse a persistência permanente das informações do sistema. Uma delas, será a de usuários.

Esta tarefa é baseada nos requisitos
```
R1.1 — O sistema dever ser capaz de armazenar dados sobre os clientes: CPF, senha, saldo, tipo de usuário.
R1.2 — O sistema deve ser capaz de distinguir usuários (clientes) em duas categorias (tipos de usuário): administrador e não-administrador.
R1.3 — O sistema deve permitir a autenticação de um usuário por um CPF e senha.
```

- Os usuários devem ser autenticados utilizando seu CPF e uma senha.

- É importantíssimo que apenas alguns dos usuários pudessem ter acesso às funções sensíveis do sistema. Para tal, o sistema deve distinguir usuários não-administradores e administradores.
Esta distinção é apenas em nível de função: administradores também são clientes. Eles também poderão comprar refeições assim que desejarem e possuírem créditos suficientes.

GanttStart: 2022-11-09
GanttDue: 2022-11-22

**Comment by Salies** [comment]
#16
Agurdando SQA.

**Comment by GuiBatalhoti** [comment]
# Defeitos identificados

## Defeito 1
É possível inserir uma refeição anterior à data atual. Ou seja, se hoje é dia 30 de Janeiro de 2023, é possível inserir uma refeição no dia 10 de Janeiro de 2023.

## Defeito 2
Na representação da Refeição, falta a identificação do "Prato Principal", mas não está presente desde o Modelo Conceitual e o Diagrama de Classes.

**Comment by GuiBatalhoti** [comment]
Nenhum defeito encontrado no SQA da parte de Representação dos Usuários.

Fechando a Issue.
