### ISSUE TITLE
Representação e adição das refeições na aplicação

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#4]
Requisitos:
```
R2.1 — O software deve ser capaz de permitir o usuário administrador inserir uma refeição que será oferecida pelo restaurante.
R2.2 — A refeição deverá conter os seguintes atributos: data de serventia, quantidade de tíquetes totais para compra disponíveis, tipo de refeição, nome da refeição, prato principal, alimentos de base, guarnição, saladas, bebida e sobremesa.

```

Como administrador, gostaria de adicionar uma refeição que será futuramente servida. 

Importante: Preciso estar autenticado como administrador para fazer isso.

GanttStart: 2022-11-09
GanttDue: 2022-11-22

**Comment by GuiBatalhoti** [comment]
# Defeitos identificados
## Defeito 1
É possível inserir uma refeição anterior à data atual. Ou seja, se hoje é dia 30 de Janeiro de 2023, é possível inserir uma refeição no dia 10 de Janeiro de 2023.

## Defeito 2
Na representação da Refeição, falta a identificação do "Prato Principal", mas não está presente desde o Modelo Conceitual e o Diagrama de Classes.

**Comment by Salies** [comment]
- Adicionei uma restrição de data. Fiz com que ainda seja possível adicionar uma refeição para "hoje", visto que logicamente isto faz sentido.
- Adicionado o prato principal, inclusive na interface de inserção de prato.

**Comment by GuiBatalhoti** [comment]
Mais nenhum defeito identificado a respeito da Representação das Refeições.

Fechando Issue.
