### ISSUE TITLE
Inserção de créditos no sistema e registro desta transação

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#5]
Como responsável pelo RU, gostaria que os administradores sejam capazes de inserir créditos aos clientes assim que receberem a quantia em moeda física (cédulas, moedas).
Para evitar fraudes, é importante que seja armazenado um registro desta inserção.

```
R3.1 — O software deve ser capaz de permitir que o administrador insira créditos para consumo para um cliente após receber a quantia corrente (moeda física: real).
R3.2 — O software deve manter registro desta transação, armazenando data, valor, o usuário administrador e o cliente beneficiado.
```

Lembrete: administradores ainda são clientes: podem receber créditos e comprar refeições.

GanttStart: 2022-11-23
GanttDue: 2022-12-06

**Comment by GuiCT** [comment]
Projeto feito no arquivo .asta na main. Aguardando SQA @GuiBatalhoti

**Comment by GuiBatalhoti** [comment]
Nenhum defeito encontrado no SQA.

**Comment by Salies** [comment]
Feature implementada em #17.
Aguradando SQA.
