### ISSUE TITLE
Visualização do calendário das refeições

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#6]
Como cliente, gostaria de visualizar o calendário de refeições do RU da semana atual e das duas próximas semanas. 

Caso eu desejar, posso visualizar mais detalhes de uma refeição específica.

```
R2.3 — O software deve ser capaz de permitir que os clientes visualizem o calendário de refeições da semana atual e da seguinte, exibindo o nome das refeições servidas.
R2.4 — O software deve ser capaz de exibir os todos os atributos de uma refeição.
```

GanttStart: 2022-11-23
GanttDue: 2022-12-06

**Comment by GuiCT** [comment]
Realizei a listagem das refeições através da recuperação das mesmas via a instância singleton "UniRestaurant" e aplicando um filter que irá filtrar todas as instâncias que estão na semana atual ou na próxima. A lista resultante desse filtro será retornada para a instância que chama esse método e então tratado via GUI.

**Comment by GuiCT** [comment]
Aguardando SQA @GuiBatalhoti

**Comment by Salies** [comment]
Implementada em #17.
Aguardando SQA.
