### ISSUE TITLE
Venda de tíquete de refeição

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#7]
Como cliente, gostaria de comprar tíquetes para as refeições servidas. Para tal, devo seguir algumas regras de boa cidadania, definidas pelo restaurante.

Requisitos:
```
R4.1 — O software deve ser capaz de permitir que o cliente compre um tíquete por refeição a ser servida.
R4.2 — O software deve decrementar o valor em créditos do cliente referente ao tíquete.
R4.3 — O software deve garantir que o cliente apenas compre um tíquete caso possua créditos suficientes no momento da aquisição, isto é, no mínimo, o valor do tíquete em crédito.
R4.4 — O software deve garantir que o cliente apenas compre uma unidade de tíquete por refeição a ser servida.
R4.5 — O software deve garantir que o cliente apenas possa comprar um tíquete para uma refeição caso não possua um tíquete para esta refeição.
R4.6 — O software deve garantir que o cliente apenas compre um tíquete caso a quantidade disponível de tíquetes for maior que zero.
R4.7 — O software deve garantir que o cliente apenas compre tíquetes até um dia antes da data de serventia.
R4.8 — O software deve decrementar a quantidade de tíquetes disponíveis para uma refeição após a compra de um tíquete dela.
```

GanttStart: 2022-12-07
GanttDue: 2022-12-22

**Comment by GuiCT** [comment]
Fiz a representação da venda de tíquetes a partir da adição de uma instância da classe "Tiquete" - responsável por identificar se o mesmo já foi utilizado ou não - à um mapa na instância de usuário.

Dessa forma, para verificar se um usuário possui um tiquete para uma determinada refeição, basta recuperar a instância da refeição referida e verificar se há uma entrada no mapa onde essa instância é chave. Para realizar a venda de um tíquete, basta adicionar uma entrada nesse mesmo mapa e realizar o decréscimo do saldo.

**Comment by GuiCT** [comment]
Aguardando SQA @GuiBatalhoti

**Comment by Salies** [comment]
Implementado seguindo as orientações do projetista. Já está na branch #17.

Aguardando SQA.
