### ISSUE TITLE
Permitir a entrada dos clientes no estabelecimento

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#8]
Como responsável pelo estabelecimento do RU, desejo que apenas clientes pagantes possam adentar o local.

```
R5.1 — O software deve ser capaz de interagir com a catraca da entrada do estabelecimento do RU, concedendo a passagem para a entrada de um cliente.
R5.2 — O software deve ser capaz de conceder a entrada de um cliente após esta pessoa inserir seu CPF na catraca e possuir (no sistema) um tíquete adquirido para a refeição a ser servida.
R5.3 — O software deve apenas conceder a entrada no restaurante para clientes com tíquete.
R5.4 — O software não deve conceder a entrada no restaurante para clientes sem tíquete.
R5.5 — O software deve ser capaz de conceder a entrada de clientes no restaurante apenas na data e período (derivado do tipo de refeição) de serventia.
R5.6 — O software deve permitir a entrada de um cliente apenas uma vez para uma refeição servida.
```

GanttStart: 2023-01-04
GanttDue: 2023-01-17

**Comment by becelli** [comment]
Início análise: 06 de janeiro, sendo histórico do Git.

**Comment by GuiBatalhoti** [comment]
# Lista de Defeitos:

## Caso de Uso: Entrada de clientes

Não foram encontrados defeitos nesse caso de uso. Não há necessidade, para o escopo do caso de uso, identificar como um evento que o usuário passou pela catraca. Apenas citar que a catraca é travada após a passagem do usuário.


# Problemas de MERGE

Foram identificados vários problemas de merge no arquivo "USE_CASES.md". Alguns casos de uso estão com inconsistências. Porém, não sei quem deverá corrigir @becelli verificar.

**Comment by GuiCT** [comment]
Elaborei um diagrama de colaboração "liberarCatraca" no arquivo .asta que visa explicar como essa permissão será concedida com base nos tíquetes que um determinado usuário possui ou não.

**Comment by Salies** [comment]
Implementação realizada #17.

Aguardando SQA.
