### ISSUE TITLE
[IMPORTANTE] Ler e aplicar as regras de trabalho

### ISSUE THREAD

**Issue by becelli** [Team-Dire/university-restaurant#9]
### Visualize o conteúdo do link abaixo:
- [📜 Regras de trabalho](https://github.com/Team-Dire/university-restaurant/blob/main/docs/WORKFLOW_RULES.md)

Após a breve leitura, comente um "ok" e aplique o procedimento indicados no documento, na ordem indicada.

---
Para mais informações: [Leia-me.](https://github.com/Team-Dire/university-restaurant/blob/main/README.md)

**Comment by G-Nozawa** [comment]
ok

**Comment by Salies** [comment]
ok corno

**Comment by GuiCT** [comment]
Ata
